#!/bin/sh
# Uncomment the following two lines for normal desktop:
# the file to Enable An Graphical View in VNC Viewer 
# vi ~/.vnc/xstartup

export XKLXMODMAPDISABLE=1
unset SESSION_MANAGER
unset DBUSSESSIONBUSADDRESS
xsetroot -solid grey
vncconfig -iconic &
x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
gnom-panel &
gnome-settings-daemon &
metacity &
nautilus &
gnome-terminal &
