#!/bin/bash
cd payload

tar cf ../payload.tar ./*

cd ..

if [ -e "payload.tar" ]; then
    gzip payload.tar

    if [ -e "payload.tar.gz" ]; then
       cat decompress payload.tar.gz > ai_pack.sh 
    else
       echo "payload.tar.gz does not exist"
       exit 1
    fi
else
    echo "payload.tar does not exist"
    exit 1

fi


echo "packaged created" 

exit 0
